version: '3.9'

services:
  plants-core:
    command: ["echo", "ğŸŒ± plants-core wird lokal in IntelliJ gestartet"]
    deploy:
      replicas: 0

  care-ui:
    command: ["echo", "ğŸ–¥ï¸ care-ui wird lokal in IntelliJ gestartet"]
    deploy:
      replicas: 0
